<a href="https://colab.research.google.com/github/nambelaas/DataMining/blob/main/datapreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


library numpy -> olah numerik di python
library pandas -> import external file csv,excel,txt

In [11]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['England' 30.0 nan]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 24.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 46.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes']


In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [16]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['England' 30.0 65000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 65000.0]
 ['France' 24.0 58000.0]
 ['Spain' 37.111111111111114 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 46.0 83000.0]
 ['France' 37.0 67000.0]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 30.0 65000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 40.0 65000.0]
 [0.0 1.0 0.0 0.0 24.0 58000.0]
 [0.0 0.0 0.0 1.0 37.111111111111114 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 46.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [20]:
print(y)

[0 1 0 0 1 0 0 1 0 1]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [22]:
print(x_train)

[[0.0 0.0 0.0 1.0 37.111111111111114 52000.0]
 [0.0 0.0 1.0 0.0 40.0 65000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 46.0 83000.0]
 [0.0 1.0 0.0 0.0 24.0 58000.0]]


In [23]:
print(x_test)

[[1.0 0.0 0.0 0.0 30.0 65000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [24]:
print(y_train)

[0 1 0 0 1 1 0 0]


In [25]:
print(y_test)

[0 1]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [27]:
print(x_train)

[[0.0 0.0 0.0 1.2909944487358056 -0.11178372270284015 -1.0915491813053724]
 [0.0 0.0 1.0 -0.7745966692414834 0.24592418994625045 0.02140292512363475]
 [0.0 1.0 0.0 -0.7745966692414834 0.741212068998838 0.6206848285854079]
 [0.0 0.0 0.0 1.2909944487358056 -0.0017197495800433157
  -0.3210438768545213]
 [0.0 0.0 0.0 1.2909944487358056 -1.363761416974659 -1.4339959832835285]
 [0.0 1.0 0.0 -0.7745966692414834 1.2364999480514256 1.219966732047181]
 [0.0 0.0 1.0 -0.7745966692414834 0.9888560085251318 1.562413534025337]
 [0.0 1.0 0.0 -0.7745966692414834 -1.7352273262640996 -0.5778789783381383]]


In [28]:
print(x_test)

[[1.0 0.0 0.0 -0.7745966692414834 -0.9922955076852183 0.02140292512363475]
 [0.0 1.0 0.0 -0.7745966692414834 -0.1255417193431902 0.19262632611271277]]
